FROM apache/airflow:2.8.0-python3.10

USER root
RUN apt-get update && apt-get install -y docker.io && rm -rf /var/lib/apt/lists/* && \
    groupadd -g 991 dockerhost || true && \
    usermod -aG dockerhost airflow

USER airflow

COPY requirements-pipeline.txt .
RUN pip install --no-cache-dir \
    -r requirements-pipeline.txt \
    --extra-index-url https://download.pytorch.org/whl/cpu

RUN python -m nltk.downloader punkt stopwords wordnet -d /home/airflow/nltk_data
RUN python -m spacy download en_core_web_sm
