FROM apache/airflow:2.8.0-python3.10

USER airflow

RUN pip install --no-cache-dir \
    nltk==3.8.1 \
    gensim==4.3.2 \
    spacy==3.7.2 \
    scikit-learn==1.3.2 \
    scipy==1.11.4 \
    tensorflow==2.15.0 \
    pandas==2.1.4 \
    pyyaml==6.0.1

RUN python -m nltk.downloader punkt stopwords wordnet -d /home/airflow/nltk_data
RUN python -m spacy download en_core_web_sm
