FROM rasa/rasa-sdk:3.4.0

WORKDIR /app

USER root
COPY requirements-actions.txt .
RUN pip install --no-cache-dir -r requirements-actions.txt

COPY actions/ ./actions/

USER 1001

EXPOSE 5055

CMD ["start", "--actions", "actions"]
